name: "noliteo-db"

services:
  postgres:
    image: postgres:18-alpine
    container_name: "postgres"
    ports:
      - 5432:5432
    volumes:
      - ~/apps/posgres:/var/lib/posgresql/data
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
