name: "quoin-core"
services:
  api:
    env_file: ".env"
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080

#   postgres:
#     image: postgres:17.5-alpine
#     restart: always
#     environment:
#       POSTGRES_DB: postgres
#       POSTGRES_USER: postgres
#       POSTGRES_PASSWORD: password 
#     ports:
#       - 5432:5432
#     healthcheck:
#       test:
#         - CMD-SHELL
#         - psql -h "db" -U $${POSTGRES_USER} -p 5432 -d $${POSTGRES_DB} -c "\q" || exit 1
#       interval: 2s
#       timeout: 3s
#       retries: 5
#     volumes:
#       - db:/var/lib/postgresql/data
#     networks:
#       app:

# networks:
#   app:

# volumes:
#   postgres:
#     driver: local